# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: fa5baa4
_src_path: gh:mcsitter/project-template
project_description: Reusable pre-commit hooks for Python projects.
project_name: Pre Commit Hooks
project_type: package
python_version: '3.12'
typing: true
with_conventional_commits: true
